name: Highway Front CI

on:
  push:
    branches:
      - master
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Version From Package.json
        id: version
        run: |
          echo "VERSION=$(grep '"version"' ./package.json | cut -d '"' -f 4)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          release_name: Version ${{ steps.version.outputs.VERSION }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions: write-all
    needs: create-release

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get Version From Package.json
        id: version
        run: |
          echo "VERSION=$(grep '"version"' ./package.json | cut -d '"' -f 4)" >> $GITHUB_OUTPUT

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6.7.0
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/highway-web:latest
            ${{ secrets.DOCKER_USERNAME }}/highway-web:${{ steps.version.outputs.VERSION }}

  kubernetes-deployment-restart:
    name: Kubernetes Deployment Restart
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Setup Kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Restart Kubernetes Deployment
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          kubectl rollout restart deployment -l app=highway-web 
